###
POST http://localhost:3000/task HTTP/1.1
Content-Type: application/json

{
  "name": "simple trigger",
  "executeAt": "2020-09-10T18:01:00+02:00",
  "message": {"hello":"world"}
}

### 
GET http://localhost:3000/task/3 HTTP/1.1
Content-Type: application/json

### 
GET http://localhost:3000/task/count HTTP/1.1
Content-Type: application/json

### 
GET http://localhost:3000/mirror HTTP/1.1
Content-Type: application/json
